# Generated by Django 4.2.7 on 2023-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('power', models.PositiveIntegerField(verbose_name='Poder')),
                ('mana_cost', models.PositiveIntegerField(verbose_name='Custo de Mana')),
                ('duration', models.PositiveIntegerField(verbose_name='Duração')),
                ('effects', models.ManyToManyField(blank=True, to='effects.effect')),
            ],
            options={
                'verbose_name_plural': 'Effects',
                'ordering': ['name'],
            },
        ),
    ]
