# Generated by Django 4.2.7 on 2023-12-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Último nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='characters.character')),
            ],
            options={
                'verbose_name_plural': 'Players',
                'ordering': ['first_name'],
            },
        ),
    ]
