# Generated by Django 4.2.7 on 2023-12-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magics', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('level', models.IntegerField(verbose_name='Nível')),
                ('magics', models.ManyToManyField(to='magics.magic')),
            ],
            options={
                'verbose_name_plural': 'Characters',
                'ordering': ['name'],
            },
        ),
    ]
