# Generated by Django 4.2.7 on 2023-12-04 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '__first__'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=10, verbose_name='Tamanho')),
                ('money', models.FloatField(verbose_name='Dinheiro')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='characters.character')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='InventorySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.item')),
            ],
        ),
    ]
