# Generated by Django 4.2.7 on 2023-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('base_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Multiplicador base')),
            ],
            options={
                'verbose_name_plural': 'Rarities',
                'ordering': ['name'],
            },
        ),
    ]
